sudo: required

services:
  - docker

before_install:
  - docker build -t symengine/ubuntu_base ./ubuntu_base
  - docker build -t symengine/conda_base ./conda_base
  - docker build -t symengine/symengine ./symengine

script:
  - docker run symengine/ubuntu_base id
  - docker run symengine/conda_base id
  - docker run symengine/symengine symengine/benchmarks/expand2
  - docker run symengine/symengine which python
  - docker run symengine/symengine python --version
  - docker run -t symengine/symengine bash -c "cd symengine/benchmarks && python run_bench.py && cat data.json"

notifications:
  email: false
