sudo: required

services:
  - docker

before_install:
  - docker build -t symengine/ubuntu_base ./ubuntu_base
  - docker build -t symengine/conda_base ./conda_base
  - docker build -t symengine/symengine ./symengine

script:
  - docker run symengine/ubuntu_base id
  - docker run symengine/conda_base id
  - docker run symengine/symengine symengine/benchmarks/expand2

notifications:
  email: false
